### ISSUE TITLE
Godot 4.0

### ISSUE THREAD

**Issue by Rizzlord** [pemguin005/Third-Person-Controller---Godot-Souls-like#4]
Hey, would you be so kind, to update it for Godot 4?

**Comment by catprisbrey** [comment]
My GitHub has a separate repo for a Godot 4 version. I will leave this repo as is, specifically for Godot 3.5 since the code is so distinct between the two.

The other project can be found here:
https://github.com/pemguin005/Third-Person-Controller--SoulsLIke-Godot4

It was rewritten on an early Godot 4 beta, and i haven't had time to try it out on 4 Stable yet. But try that out and see if it works for you
